// <auto-generated />
using HotelsApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelsApi.Migrations
{
    [DbContext(typeof(HotelsContext))]
    partial class HotelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelsApi.Models.Hotel", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(128);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(64);

                    b.HasKey("ID");

                    b.ToTable("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
